export const LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS";
export const SAVE_EMPLOYEE_SUCCESS = "CREATE_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_SUCESS = "DELETE_EMPLOYEE_SUCESS";
